# -*- coding: utf-8 -*-
"""Project 129

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ysjlCxHHsJs_4nqwSi0PP5j3joqd6c7u
"""

import pandas as pd
df = pd.read_csv("dwarfstars.csv")
df.head()
df.columns()
df.dtypes()
df = df.dropna()
df.dtypes()
df["Radius"] = 0.102763*df["Radius"]
df["Mass"] = df["Mass"].apply(lambda x: x.replace('$', '').replace(',', '')).astype('float')
df["Mass"] = 0.000954588*df["Mass"]
df.drop(['Unnamed: 0'], axis = 1, inplace = True)
df.reset_index(drop = True, inplace = True)
df.to_csv("convertedstars.csv")